#!/usr/bin/env bash
# Starship OS — select hardware profile (edge | server | ops)
# Writes /etc/starship/profile.yaml (root) or ~/.config/starship/profile.yaml
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROFILES_SRC="$REPO_DIR/config/profiles.yaml"
FORCE_PROFILE="${1:-${STARSHIP_PROFILE:-}}"

if [[ "$(id -u)" == "0" ]]; then
  OUT_DIR="/etc/starship"
else
  OUT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/starship"
fi
mkdir -p "$OUT_DIR"
OUT_FILE="$OUT_DIR/profile.yaml"

ram_mb=$(free -m 2>/dev/null | awk '/^Mem:/{print $2}' || echo 0)
vram_mb=0
gpu_vendor="none"
gpu_name=""

if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
  gpu_vendor="nvidia"
  gpu_name=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 | sed 's/^ *//')
  vram_mb=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ' || echo 0)
elif [[ -e /dev/kfd ]] || command -v rocm-smi &>/dev/null; then
  gpu_vendor="amd"
  gpu_name="AMD ROCm"
  # best-effort VRAM
  vram_mb=$(rocm-smi --showmeminfo vram 2>/dev/null | grep -oP 'Total Memory \(B\):\s*\K[0-9]+' | head -1 || echo 0)
  if [[ "${vram_mb:-0}" -gt 0 ]]; then
    vram_mb=$((vram_mb / 1024 / 1024))
  fi
fi

if [[ -n "$FORCE_PROFILE" ]]; then
  profile="$FORCE_PROFILE"
else
  if [[ "${vram_mb:-0}" -ge 6144 && "${ram_mb:-0}" -ge 16384 ]]; then
    profile="ops"
  elif [[ "${vram_mb:-0}" -ge 4096 || "${ram_mb:-0}" -ge 8192 ]]; then
    profile="server"
  else
    profile="edge"
  fi
fi

case "$profile" in
  edge|server|ops) ;;
  *) echo "Unknown profile: $profile (use edge|server|ops)" >&2; exit 1 ;;
esac

# num_ctx / nats_mode from profile defaults
case "$profile" in
  edge) num_ctx=8192; nats_mode=agent ;;
  server) num_ctx=16384; nats_mode=agent ;;
  ops) num_ctx=32768; nats_mode=fleet ;;
esac

cat > "$OUT_FILE" <<EOF
# Generated by select-profile.sh — do not hand-edit (re-run script)
profile: $profile
selected_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
hardware:
  ram_mb: ${ram_mb:-0}
  vram_mb: ${vram_mb:-0}
  gpu_vendor: $gpu_vendor
  gpu_name: "$gpu_name"
  arch: $(uname -m)
  cores: $(nproc 2>/dev/null || echo 1)
settings:
  num_ctx: $num_ctx
  dashboard_port: 8788
  nats_mode: $nats_mode
  nats_prefix: starship
  nats_legacy_prefix: agnetic
source_profiles: $PROFILES_SRC
EOF

echo "Profile: $profile"
echo "  RAM:    ${ram_mb} MB"
echo "  VRAM:   ${vram_mb} MB ($gpu_vendor)"
echo "  Wrote:  $OUT_FILE"

# Optional: emit model pull list for installers
if command -v python3 &>/dev/null && [[ -f "$PROFILES_SRC" ]]; then
  python3 - "$PROFILES_SRC" "$profile" <<'PY' 2>/dev/null || true
import sys, yaml
from pathlib import Path
src, name = sys.argv[1], sys.argv[2]
data = yaml.safe_load(Path(src).read_text())
p = data["profiles"][name]
req = p.get("models", {}).get("required", [])
print("Models (required):", ", ".join(req))
PY
fi
