#!/usr/bin/env bash
# Starship OS — first boot after autoinstall / package install
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="/etc/starship/firstboot.env"
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
fi

PROFILE="${STARSHIP_PROFILE:-server}"
# Force fleet-bus: ops profile, or STARSHIP_FLEET_BUS=1
ENABLE_FLEET_BUS="${STARSHIP_FLEET_BUS:-}"
mkdir -p /etc/starship /etc/starship/nats /opt/starship /var/lib/starship /var/lib/starship/nats /var/log/starship
ln -sfn /opt/starship /opt/agnetic 2>/dev/null || true
ln -sfn /etc/starship /etc/agnetic 2>/dev/null || true
ln -sfn /var/lib/starship /var/lib/agnetic 2>/dev/null || true

echo "=== Starship firstboot (profile=$PROFILE) ==="

# 1) Profile selection (force profile from autoinstall)
if [[ -x "$REPO_DIR/scripts/select-profile.sh" ]]; then
  bash "$REPO_DIR/scripts/select-profile.sh" "$PROFILE" || true
else
  echo "profile: $PROFILE" > /etc/starship/profile.yaml
fi

# 2) GPU / Ollama env
if [[ -x "$REPO_DIR/scripts/detect-gpu.sh" ]]; then
  bash "$REPO_DIR/scripts/detect-gpu.sh" || true
fi

# 3) Models for profile
if [[ -x "$REPO_DIR/scripts/install-models.sh" ]]; then
  bash "$REPO_DIR/scripts/install-models.sh" "$PROFILE" || true
fi

# 4) Fleet topology + node registration
if [[ -f "$REPO_DIR/config/fleet.yaml" ]]; then
  cp "$REPO_DIR/config/fleet.yaml" /etc/starship/fleet.yaml
fi
# Map profile → default plant
case "$PROFILE" in
  edge) PLANT=plant-edge; ROLES="proxy,plant-controller" ;;
  ops)  PLANT=plant-alpha; ROLES="proxy,romi,ergo,ops" ;;
  *)    PLANT=plant-alpha; ROLES="proxy,romi,ergo" ;;
esac
ROLES_CSV="${STARSHIP_FLEET_ROLES:-$ROLES}"
ROLES_YAML=$(echo "$ROLES_CSV" | awk -F, '{for(i=1;i<=NF;i++){gsub(/^ +| +$/,"",$i); printf "%s\"%s\"", (i>1?", ":""), $i}}')
cat > /etc/starship/fleet-node.yaml <<EOF
node:
  plant: ${STARSHIP_FLEET_PLANT:-$PLANT}
  roles: [${ROLES_YAML}]
  team: ${STARSHIP_FLEET_TEAM:-ops}
  profile: $PROFILE
EOF

# 4b) NATS bus selection — agent-bus (local) vs fleet-bus (ops multi-node)
_install_nats_configs() {
  local nats_src=""
  if [[ -d "$REPO_DIR/nats" ]]; then
    nats_src="$REPO_DIR/nats"
  elif [[ -d /opt/starship/lib/starship/nats ]]; then
    nats_src=/opt/starship/lib/starship/nats
  fi
  [[ -n "$nats_src" ]] || return 0
  mkdir -p /etc/starship/nats
  cp "$nats_src/agent-bus.conf" /etc/starship/nats/ 2>/dev/null || true
  cp "$nats_src/fleet-bus.conf" /etc/starship/nats/ 2>/dev/null || true
  cp "$nats_src/fleet-auth.yaml" /etc/starship/nats/ 2>/dev/null || true
  cp "$nats_src/subjects.yaml" /etc/starship/nats/ 2>/dev/null || true
}

_gen_nats_token() {
  if [[ -n "${STARSHIP_NATS_TOKEN:-}" ]]; then
    echo "$STARSHIP_NATS_TOKEN"
    return
  fi
  if [[ -f /etc/starship/nats-token ]]; then
    cat /etc/starship/nats-token
    return
  fi
  # 32-byte hex token
  if command -v openssl &>/dev/null; then
    openssl rand -hex 24
  else
    head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

_enable_fleet_bus() {
  echo "NATS mode: fleet-bus (ops multi-node auth)"
  _install_nats_configs
  local token
  token="$(_gen_nats_token)"
  umask 077
  printf '%s\n' "$token" > /etc/starship/nats-token
  chmod 640 /etc/starship/nats-token 2>/dev/null || true
  chown root:nats /etc/starship/nats-token 2>/dev/null || chown root:root /etc/starship/nats-token 2>/dev/null || true

  # Materialize fleet-bus.conf with real token (never leave placeholder)
  local conf_src="/etc/starship/nats/fleet-bus.conf"
  if [[ ! -f "$conf_src" && -f "$REPO_DIR/nats/fleet-bus.conf" ]]; then
    cp "$REPO_DIR/nats/fleet-bus.conf" "$conf_src"
  fi
  if [[ -f "$conf_src" ]]; then
    sed "s|__STARSHIP_NATS_TOKEN__|${token}|g" "$conf_src" > /etc/starship/nats/fleet-bus.active.conf
    # Also rewrite token if conf was already materialized once
    if ! grep -q "$token" /etc/starship/nats/fleet-bus.active.conf 2>/dev/null; then
      sed -i "s|token: \".*\"|token: \"${token}\"|" /etc/starship/nats/fleet-bus.active.conf 2>/dev/null || true
    fi
    ln -sfn /etc/starship/nats/fleet-bus.active.conf /etc/starship/nats/active.conf
  else
    echo "warn: fleet-bus.conf missing — falling back to agent-bus" >&2
    ln -sfn /etc/starship/nats/agent-bus.conf /etc/starship/nats/active.conf
    return 0
  fi

  local host="${STARSHIP_NATS_HOST:-127.0.0.1}"
  cat > /etc/starship/nats.env <<EOF
# Generated by starship-firstboot — fleet-bus mode
STARSHIP_NATS_TOKEN=${token}
NATS_URL=nats://${host}:4222
STARSHIP_NATS_MODE=fleet
EOF
  chmod 640 /etc/starship/nats.env 2>/dev/null || true
  chown root:agnetic /etc/starship/nats.env 2>/dev/null || true

  cat > /etc/starship/fleet.env <<EOF
# Generated by starship-firstboot
STARSHIP_FLEET_PLANT=${STARSHIP_FLEET_PLANT:-$PLANT}
STARSHIP_FLEET_TEAM=${STARSHIP_FLEET_TEAM:-ops}
STARSHIP_FLEET_ROLES=${ROLES_CSV}
STARSHIP_NATS_MODE=fleet
EOF
  chmod 644 /etc/starship/fleet.env 2>/dev/null || true

  # Optional cluster routes snippet
  if [[ -n "${STARSHIP_NATS_ROUTES:-}" && -f /etc/starship/nats/fleet-bus.active.conf ]]; then
    if ! grep -q '^cluster {' /etc/starship/nats/fleet-bus.active.conf; then
      cat >> /etc/starship/nats/fleet-bus.active.conf <<CLUSTEREOF

cluster {
  name: starship-fleet
  port: 6222
  routes: [
    ${STARSHIP_NATS_ROUTES}
  ]
}
CLUSTEREOF
    fi
  fi

  mkdir -p /var/lib/starship/nats
  chown nats:nats /var/lib/starship/nats 2>/dev/null || true
  echo "  active.conf → fleet-bus (token set, host=${host})"
}

_enable_agent_bus() {
  echo "NATS mode: agent-bus (local dev / server / edge)"
  _install_nats_configs
  if [[ -f /etc/starship/nats/agent-bus.conf ]]; then
    ln -sfn /etc/starship/nats/agent-bus.conf /etc/starship/nats/active.conf
  elif [[ -f "$REPO_DIR/nats/agent-bus.conf" ]]; then
    cp "$REPO_DIR/nats/agent-bus.conf" /etc/starship/nats/
    ln -sfn /etc/starship/nats/agent-bus.conf /etc/starship/nats/active.conf
  fi
  cat > /etc/starship/nats.env <<EOF
# Generated by starship-firstboot — agent-bus mode (no token)
NATS_URL=nats://127.0.0.1:4222
STARSHIP_NATS_MODE=agent
EOF
  chmod 644 /etc/starship/nats.env 2>/dev/null || true
  cat > /etc/starship/fleet.env <<EOF
STARSHIP_FLEET_PLANT=${STARSHIP_FLEET_PLANT:-$PLANT}
STARSHIP_FLEET_TEAM=${STARSHIP_FLEET_TEAM:-ops}
STARSHIP_FLEET_ROLES=${ROLES_CSV}
STARSHIP_NATS_MODE=agent
EOF
  echo "  active.conf → agent-bus"
}

_enable_accounts_bus() {
  echo "NATS mode: multi-tenant accounts + nkeys"
  _install_nats_configs
  local gen="$REPO_DIR/scripts/gen-nats-accounts.sh"
  local out="/etc/starship/nats"
  mkdir -p "$out/creds" /var/lib/starship/nats
  if [[ -x "$gen" || -f "$gen" ]]; then
    STARSHIP_NATS_HOST="${STARSHIP_NATS_HOST:-127.0.0.1}" \
      bash "$gen" --out "$out" --host "${STARSHIP_NATS_HOST:-127.0.0.1}" || true
  fi
  if [[ -f "$out/fleet-accounts.conf" ]]; then
    ln -sfn "$out/fleet-accounts.conf" /etc/starship/nats/active.conf
  else
    echo "warn: fleet-accounts.conf missing — falling back to fleet-bus token" >&2
    _enable_fleet_bus
    return 0
  fi
  # Install ops client env for fleet daemon
  if [[ -f "$out/nats.env" ]]; then
    cp "$out/nats.env" /etc/starship/nats.env
    chmod 640 /etc/starship/nats.env 2>/dev/null || true
    chown root:agnetic /etc/starship/nats.env 2>/dev/null || true
  elif [[ -f "$out/creds/ops.env" ]]; then
    cp "$out/creds/ops.env" /etc/starship/nats.env
    chmod 640 /etc/starship/nats.env 2>/dev/null || true
  fi
  # Map profile → default NATS role env
  local role_env="ops"
  case "$PROFILE" in
    edge) role_env="edge" ;;
    ops) role_env="ops" ;;
  esac
  if [[ -n "${STARSHIP_FLEET_TEAM:-}" ]]; then
    case "${STARSHIP_FLEET_TEAM}" in
      red) role_env="red" ;;
      blue) role_env="blue" ;;
    esac
  fi
  if [[ -f "$out/creds/${role_env}.env" ]]; then
    cp "$out/creds/${role_env}.env" /etc/starship/nats.env
    chmod 640 /etc/starship/nats.env 2>/dev/null || true
  fi
  cat > /etc/starship/fleet.env <<EOF
STARSHIP_FLEET_PLANT=${STARSHIP_FLEET_PLANT:-$PLANT}
STARSHIP_FLEET_TEAM=${STARSHIP_FLEET_TEAM:-ops}
STARSHIP_FLEET_ROLES=${ROLES_CSV}
STARSHIP_NATS_MODE=accounts
STARSHIP_NATS_ROLE=${role_env}
STARSHIP_SANDBOX_NATIVE=1
EOF
  # Ops: prefer C11 sandbox_run for shell tools
  if ! grep -q '^STARSHIP_SANDBOX_NATIVE=' /etc/starship/nats.env 2>/dev/null; then
    echo "STARSHIP_SANDBOX_NATIVE=1" >> /etc/starship/nats.env
  fi
  # Optional TLS (STARSHIP_NATS_TLS=1)
  if [[ "${STARSHIP_NATS_TLS:-}" == "1" || "${STARSHIP_NATS_TLS:-}" == "true" ]]; then
    local tls_gen="$REPO_DIR/scripts/gen-nats-tls.sh"
    if [[ -f "$tls_gen" ]]; then
      bash "$tls_gen" --out /etc/starship/nats/tls --host "${STARSHIP_NATS_TLS_HOST:-$(hostname -f 2>/dev/null || echo localhost)}" || true
    fi
    if [[ -f /etc/starship/nats/tls/tls.conf.snippet && -f /etc/starship/nats/fleet-accounts.conf ]]; then
      if ! grep -q '^tls {' /etc/starship/nats/fleet-accounts.conf; then
        cat /etc/starship/nats/tls/tls.conf.snippet >> /etc/starship/nats/fleet-accounts.conf
      fi
      if [[ -f /etc/starship/nats/tls/client.env ]]; then
        # merge TLS env into nats.env without clobbering user/pass
        grep -E '^(STARSHIP_NATS_TLS|STARSHIP_NATS_CA|STARSHIP_NATS_CERT|STARSHIP_NATS_KEY)=' \
          /etc/starship/nats/tls/client.env >> /etc/starship/nats.env 2>/dev/null || true
        # rewrite NATS_URL scheme to tls://
        sed -i 's|^NATS_URL=nats://|NATS_URL=tls://|' /etc/starship/nats.env 2>/dev/null || true
      fi
      echo "  TLS: enabled (/etc/starship/nats/tls)"
    fi
  fi

  chown nats:nats /var/lib/starship/nats 2>/dev/null || true
  echo "  active.conf → fleet-accounts (role=${role_env})"
}

# Bus selection:
#   STARSHIP_NATS_ACCOUNTS=1  → multi-tenant accounts/nkeys
#   ops profile or STARSHIP_FLEET_BUS=1 → fleet-bus token
#   else → agent-bus (local)
if [[ "${STARSHIP_NATS_ACCOUNTS:-}" == "1" || "${STARSHIP_NATS_ACCOUNTS:-}" == "true" || "${STARSHIP_NATS_MODE:-}" == "accounts" ]]; then
  _enable_accounts_bus
elif [[ "$PROFILE" == "ops" || "$ENABLE_FLEET_BUS" == "1" || "$ENABLE_FLEET_BUS" == "true" ]]; then
  # ops defaults to accounts when generator present; token fleet-bus otherwise
  if [[ -f "$REPO_DIR/scripts/gen-nats-accounts.sh" && "${STARSHIP_NATS_MODE:-accounts}" == "accounts" ]]; then
    _enable_accounts_bus
  else
    _enable_fleet_bus
  fi
else
  _enable_agent_bus
fi

# Register node (after nats env so token is available)
export STARSHIP_NATS_TOKEN="${STARSHIP_NATS_TOKEN:-$(cat /etc/starship/nats-token 2>/dev/null || true)}"
# shellcheck disable=SC1091
[[ -f /etc/starship/nats.env ]] && set -a && source /etc/starship/nats.env && set +a
if [[ -f "$REPO_DIR/services/fleet.py" ]]; then
  python3 "$REPO_DIR/services/fleet.py" register || true
elif [[ -f /opt/starship/lib/starship/services/fleet.py ]]; then
  python3 /opt/starship/lib/starship/services/fleet.py register || true
fi

# 5) Enable mesh + fleet if units present
if command -v systemctl &>/dev/null; then
  systemctl daemon-reload 2>/dev/null || true
  systemctl enable --now agnetic-mesh.target 2>/dev/null || true
  systemctl enable --now agnetic-nats.service 2>/dev/null || true
  systemctl enable --now starship-fleet.service 2>/dev/null || true
  # Restart NATS so active.conf takes effect
  systemctl try-restart agnetic-nats.service 2>/dev/null || true
  systemctl try-restart starship-fleet.service 2>/dev/null || true
fi

# 6) OpenCode + pantheon config (server/ops; skip edge unless forced)
if [[ "$PROFILE" == "ops" || "$PROFILE" == "server" || "${STARSHIP_INSTALL_OPENCODE:-}" == "1" ]]; then
  echo "OpenCode: installing pantheon preset..."
  OC_INSTALL=""
  for p in \
    "$REPO_DIR/scripts/install-opencode.sh" \
    /opt/starship/bin/install-opencode.sh \
    /opt/starship/lib/starship/scripts/install-opencode.sh; do
    if [[ -f "$p" ]]; then OC_INSTALL="$p"; break; fi
  done
  if [[ -n "$OC_INSTALL" ]]; then
    bash "$OC_INSTALL" || echo "warn: OpenCode install failed (npm/network optional)"
  else
    # At least install pantheon config
    mkdir -p /etc/starship/opencode
    for cfg in \
      "$REPO_DIR/config/opencode/oh-my-opencode-slim.starship.json" \
      /opt/starship/etc/opencode/oh-my-opencode-slim.starship.json; do
      if [[ -f "$cfg" ]]; then
        cp "$cfg" /etc/starship/opencode/oh-my-opencode-slim.json
        echo "  pantheon config → /etc/starship/opencode/oh-my-opencode-slim.json"
        break
      fi
    done
  fi
  # Red-team never gets OpenCode unrestricted — document policy
  cat > /etc/starship/opencode/POLICY.md <<'OCPOL'
# OpenCode policy (Starship OS)
- OpenCode pantheon is for coding/ops agents only.
- Red-team fleet roles must not receive unrestricted OpenCode (fleet_policy).
- Config: /etc/starship/opencode/oh-my-opencode-slim.json
OCPOL
fi

NATS_MODE=$(grep -E '^STARSHIP_NATS_MODE=' /etc/starship/nats.env 2>/dev/null | cut -d= -f2 || echo agent)
echo "Firstboot complete. Dashboard: http://localhost:8788"
echo "CLI: starshipctl tui  |  starshipctl fleet status"
echo "NATS: mode=${NATS_MODE} conf=$(readlink -f /etc/starship/nats/active.conf 2>/dev/null || echo n/a)"
echo "TUI:  starshipctl tui"
